language: rust
rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose
  - cd example && cargo run --features=opt1

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - develop
    - master
